[package]
name = "kaleido-app"
description = "Kaleido — randomizer, éditeur de ROM et de sauvegardes Pokémon"
version.workspace = true
edition.workspace = true
license.workspace = true

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
tauri-plugin-opener = "2"
serde.workspace = true
serde_json.workspace = true
kaleido-core.workspace = true
ureq = "2"
zip = { version = "2", default-features = false, features = ["deflate"] }
aes = "0.8"
md-5 = "0.10"
sevenz-rust2 = { version = "0.23", default-features = false, features = ["util"] }
