[package]
name = "kaleido-core"
description = "Modèle de données Pokémon, base des jeux et détection des fichiers"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
rand = "0.8"
rand_chacha = "0.3"
base64 = "0.22"
thiserror.workspace = true
kaleido-formats.workspace = true
sha1 = "0.10"
sha2 = "0.10"
aes = "0.8"
num-bigint = "0.4"
symphonia-core = "0.5.4"
symphonia-codec-aac = "0.5.4"

[dev-dependencies]
serde_json.workspace = true
